apiVersion: apps/v1 #aca el grupo de de kubectl api-resources
kind: Deployment # el nombre que sele tiene que colocar, se puede ver con kubectl api-resources
metadata:
  annotations: # anotaciones para que en el history nos aparezca 
    kubernetes.io/change-cause: "Creacion de Servicio" #Mensaje descriptivo para que aparezca en el en el historial 
  name: depback #Nobmre del deployment
  labels:
    app: Tarjeta #Label 
spec: #Replicaset que va tener el deployment
  revisionHistoryLimit: 10 #Este es el liminte de replicase creados por el deployment, por defecto viene 10 
  replicas: 3 
  selector:
    matchLabels: #Nombre que va a buscar en todos los pods
      app: Tarjeta
  template:
    metadata:
      labels:
        app: Tarjeta
    spec: #Especificacoin del contenedor
      containers:
      - name: tarejta_regalo
        image: "Nombre de la imagen"
--- #Inicia el servicio
apiVersion: v1 #aca el grupo de de kubectl api-resources
kind: Service # el nombre que sele tiene que colocar, se puede ver con kubectl api-resources  
metadata:
  name: my-servicestarjeta #FUNCIONA COMO DNS
  labels:
    app: tarjeta
spec:
  type: NodePort # Es el tipo de Cluster que se le quiere asingar al Cluster
  selector: #este es nombre o el label que se va estar utilizando 
    app: tarjeta #app.kubernetes.io/name: backend #Nombre de servicio 
  ports:
    - protocol: TCP
      port: 3005 # puerto en donde escucha la app 
      targetPort: 3005 #a que puerto del PODS se va a consumir
